#!/usr/bin/env python3
"""
Reads webapp/index.html and writes esp32/web_app.h containing the HTML
as a PROGMEM C string literal, ready to be served by the ESP32 web server.

Run automatically by `make build`. Do not run by hand unless testing.
"""

import pathlib
import sys

SRC  = pathlib.Path("webapp/index.html")
DEST = pathlib.Path("esp32/web_app.h")


def main() -> None:
    if not SRC.exists():
        print(f"Error: {SRC} not found. Run from the project root.", file=sys.stderr)
        sys.exit(1)

    html = SRC.read_text(encoding="utf-8")

    # Escape the closing raw-string delimiter if it ever appears in the HTML
    # (extremely unlikely, but safe to handle)
    html = html.replace(")rawhtml\"", ") rawhtml\"")

    header = f"""\
// Auto-generated by scripts/embed_webapp.py — do not edit manually.
// Source: {SRC}
#pragma once

const char INDEX_HTML[] PROGMEM = R"rawhtml(
{html})rawhtml";
"""

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(header, encoding="utf-8")
    print(f"Embedded {SRC} → {DEST} ({len(html)} bytes)")


if __name__ == "__main__":
    main()
